DROP DATABASE IF EXISTS encrypt;
CREATE DATABASE encrypt;
USE encrypt;
CREATE TABLE encrypted_text (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
encrypted_data VARBINARY(3000) NOT NULL,
iv VARBINARY(16) NOT NULL
);